// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMSapp.Logic.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921075302_AddLmsEntityUpdates")]
    partial class AddLmsEntityUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("AppUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Assignments", b =>
                {
                    b.Property<int>("AssignmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentsId"));

                    b.Property<string>("AssignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AvailableDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxPoints")
                        .HasColumnType("numeric");

                    b.Property<int>("SectionsId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("AssignmentsId");

                    b.HasIndex("SectionsId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Courses", b =>
                {
                    b.Property<int>("CoursesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoursesId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SyllabusExp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CoursesId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Enrollments", b =>
                {
                    b.Property<int>("EnrollmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentsId"));

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinishGrade")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SectionsId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("EnrollmentsId");

                    b.HasIndex("SectionsId");

                    b.HasIndex("StudentsId", "SectionsId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstructorId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Office")
                        .HasColumnType("text");

                    b.HasKey("InstructorId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Sections", b =>
                {
                    b.Property<int>("SectionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionsId"));

                    b.Property<TimeSpan?>("ClassTime")
                        .HasColumnType("interval");

                    b.Property<int>("CoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SemestersId")
                        .HasColumnType("integer");

                    b.HasKey("SectionsId");

                    b.HasIndex("CoursesId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SemestersId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Semesters", b =>
                {
                    b.Property<int>("SemestersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemestersId"));

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("SemestersId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Students", b =>
                {
                    b.Property<int>("StudentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentsId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<int?>("StudentNumber")
                        .HasColumnType("integer");

                    b.HasKey("StudentsId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Submissions", b =>
                {
                    b.Property<int>("SubmissionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionsId"));

                    b.Property<int>("AssignmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("EnrollmentsId")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("numeric");

                    b.Property<string>("GradeFeedback")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GradingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubmissionsId");

                    b.HasIndex("EnrollmentsId");

                    b.HasIndex("AssignmentsId", "EnrollmentsId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Assignments", b =>
                {
                    b.HasOne("Sections", "Section")
                        .WithMany("assignments")
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Enrollments", b =>
                {
                    b.HasOne("Sections", "Section")
                        .WithMany("enrollments")
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Students", "Student")
                        .WithMany("enrollments")
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Instructor", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("Instructor", "AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sections", b =>
                {
                    b.HasOne("Courses", "Course")
                        .WithMany("sections")
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Instructor", "Instructor")
                        .WithMany("sections")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Semesters", "Semester")
                        .WithMany("sections")
                        .HasForeignKey("SemestersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Students", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("Students", "AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Submissions", b =>
                {
                    b.HasOne("Assignments", "Assignment")
                        .WithMany("submissions")
                        .HasForeignKey("AssignmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Enrollments", "Enrollment")
                        .WithMany("submissions")
                        .HasForeignKey("EnrollmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Assignments", b =>
                {
                    b.Navigation("submissions");
                });

            modelBuilder.Entity("Courses", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("Enrollments", b =>
                {
                    b.Navigation("submissions");
                });

            modelBuilder.Entity("Instructor", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("Sections", b =>
                {
                    b.Navigation("assignments");

                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("Semesters", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("Students", b =>
                {
                    b.Navigation("enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
